language: php
php:
- '5.6'
- '7.0'
- '7.1'
addons:
  firefox: latest
cache:
  directories:
    - '$HOME/.sonar/cache'
script:
# Build
- vendor/bin/phing -f build/phing/build.xml
# Disable tests for now mv tests/acceptance.suite.dist.yml tests/acceptance.suite.yml
# Disable tests for now vendor/bin/robo run:tests --use-htaccess
