# Forces new Travis-CI Infrastructure
sudo: false

language: php

addons:
  firefox: "55.0"
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - xvfb
    - fluxbox

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: 7.2
    - php: nightly

before_script:
  # Composer
  - composer install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &

script:
  - vendor/bin/phing -f build/phing/build.xml
  - mv tests/acceptance.suite.dist.yml tests/acceptance.suite.yml
  - vendor/bin/robo run:tests --use-htaccess

branches:
  except:
    - K5.0
